- name: Install zsh
  apt: name=zsh
  tags:
  - zsh
- name: Change shell
  shell: chsh -s `which zsh`
  tags:
  - zsh
- name: Install omz
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
  - zsh
- name: Install zsh-syntax-highlighting plugin for omz
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
  tags:
  - zsh
- name: Install zsh-autosuggestions plugin for omz
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
  - zsh
- name: Update zshrc
  shell: sed -i 's/(git/(git zsh-autosuggestions zsh-syntax-highlighting' ~/.zshrc
  tags:
    - zsh
